# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Resp1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import serial
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

global signalWP # WPF
global signalSP # SPF
global signalM  #MF
global signalMStatus  ## MR, MH
global signalWL #  WLL
global signalSL #  S

chk = 0
finish = 0;

count = 0;
ser = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
ser.flush()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 842)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(181, 243, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.topLeft = QtWidgets.QFrame(self.top)
        self.topLeft.setStyleSheet("border: 2px solid black;")
        self.topLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLeft.setObjectName("topLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topLeft)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.waterLevelLabel = QtWidgets.QLabel(self.topLeft)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.waterLevelLabel.setFont(font)
        self.waterLevelLabel.setStyleSheet("border:none;")
        self.waterLevelLabel.setObjectName("waterLevelLabel")
        self.verticalLayout_2.addWidget(self.waterLevelLabel, 0, QtCore.Qt.AlignHCenter)
        self.waterLevelSensor = QtWidgets.QLabel(self.topLeft)
        self.waterLevelSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.waterLevelSensor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.waterLevelSensor.setText("")
        self.waterLevelSensor.setPixmap(QtGui.QPixmap("icons8-water-level-60.png"))
        self.waterLevelSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.waterLevelSensor.setObjectName("waterLevelSensor")
        self.verticalLayout_2.addWidget(self.waterLevelSensor)
        self.horizontalLayout.addWidget(self.topLeft)
        self.topMiddle = QtWidgets.QFrame(self.top)
        self.topMiddle.setStyleSheet("border: 2px solid black;")
        self.topMiddle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMiddle.setObjectName("topMiddle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.topMiddle)
        self.verticalLayout_3.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tempLabel = QtWidgets.QLabel(self.topMiddle)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.tempLabel.setFont(font)
        self.tempLabel.setStyleSheet("border: none;")
        self.tempLabel.setObjectName("tempLabel")
        self.verticalLayout_3.addWidget(self.tempLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.temperature = QtWidgets.QLCDNumber(self.topMiddle)
        self.temperature.setFrameShape(QtWidgets.QFrame.Box)
        self.temperature.setObjectName("temperature")
        self.verticalLayout_3.addWidget(self.temperature)
        self.horizontalLayout.addWidget(self.topMiddle)
        self.topRight = QtWidgets.QFrame(self.top)
        self.topRight.setMinimumSize(QtCore.QSize(500, 0))
        self.topRight.setStyleSheet("border: 2px solid black;")
        self.topRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topRight.setObjectName("topRight")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.topRight)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topRightUp = QtWidgets.QFrame(self.topRight)
        self.topRightUp.setStyleSheet("border: none;")
        self.topRightUp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topRightUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topRightUp.setObjectName("topRightUp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.topRightUp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sensorStatusLabel = QtWidgets.QLabel(self.topRightUp)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.sensorStatusLabel.setFont(font)
        self.sensorStatusLabel.setStyleSheet("border: none;")
        self.sensorStatusLabel.setObjectName("sensorStatusLabel")
        self.verticalLayout_5.addWidget(self.sensorStatusLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sensorStatusLabels = QtWidgets.QFrame(self.topRightUp)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sensorStatusLabels.setFont(font)
        self.sensorStatusLabels.setStyleSheet("border: none;")
        self.sensorStatusLabels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensorStatusLabels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensorStatusLabels.setObjectName("sensorStatusLabels")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.sensorStatusLabels)
        self.horizontalLayout_15.setContentsMargins(40, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(35)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.homeSensorLabel = QtWidgets.QLabel(self.sensorStatusLabels)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.homeSensorLabel.setFont(font)
        self.homeSensorLabel.setObjectName("homeSensorLabel")
        self.horizontalLayout_15.addWidget(self.homeSensorLabel)
        self.forwardSensoLabel = QtWidgets.QLabel(self.sensorStatusLabels)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.forwardSensoLabel.setFont(font)
        self.forwardSensoLabel.setObjectName("forwardSensoLabel")
        self.horizontalLayout_15.addWidget(self.forwardSensoLabel)
        self.reverseSensorLabel = QtWidgets.QLabel(self.sensorStatusLabels)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reverseSensorLabel.setFont(font)
        self.reverseSensorLabel.setObjectName("reverseSensorLabel")
        self.horizontalLayout_15.addWidget(self.reverseSensorLabel)
        self.verticalLayout_5.addWidget(self.sensorStatusLabels, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_4.addWidget(self.topRightUp)
        self.topRightDown = QtWidgets.QFrame(self.topRight)
        self.topRightDown.setStyleSheet("border: none;")
        self.topRightDown.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topRightDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topRightDown.setObjectName("topRightDown")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topRightDown)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.home = QtWidgets.QFrame(self.topRightDown)
        self.home.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home.setObjectName("home")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.home)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.homeSensor = QtWidgets.QLabel(self.home)
        self.homeSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.homeSensor.setText("")
        self.homeSensor.setPixmap(QtGui.QPixmap("icons8-home-100.png"))
        self.homeSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.homeSensor.setObjectName("homeSensor")
        self.horizontalLayout_3.addWidget(self.homeSensor)
        self.horizontalLayout_2.addWidget(self.home)
        self.forward = QtWidgets.QFrame(self.topRightDown)
        self.forward.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.forward.setFrameShadow(QtWidgets.QFrame.Raised)
        self.forward.setObjectName("forward")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.forward)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.forwardSensor = QtWidgets.QLabel(self.forward)
        self.forwardSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.forwardSensor.setText("")
        self.forwardSensor.setPixmap(QtGui.QPixmap("icons8-fast-forward-100.png"))
        self.forwardSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.forwardSensor.setObjectName("forwardSensor")
        self.horizontalLayout_4.addWidget(self.forwardSensor)
        self.horizontalLayout_2.addWidget(self.forward)
        self.reverse = QtWidgets.QFrame(self.topRightDown)
        self.reverse.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.reverse.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reverse.setObjectName("reverse")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.reverse)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.reverseSensor = QtWidgets.QLabel(self.reverse)
        self.reverseSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.reverseSensor.setText("")
        self.reverseSensor.setPixmap(QtGui.QPixmap("icons8-rewind-100.png"))
        self.reverseSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.reverseSensor.setObjectName("reverseSensor")
        self.verticalLayout_6.addWidget(self.reverseSensor)
        self.horizontalLayout_2.addWidget(self.reverse)
        self.verticalLayout_4.addWidget(self.topRightDown)
        self.horizontalLayout.addWidget(self.topRight)
        self.verticalLayout.addWidget(self.top)
        self.middle = QtWidgets.QFrame(self.centralwidget)
        self.middle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle.setObjectName("middle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.middle)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.middleLeft = QtWidgets.QFrame(self.middle)
        self.middleLeft.setStyleSheet("border: 2px solid black;")
        self.middleLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middleLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middleLeft.setObjectName("middleLeft")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.middleLeft)
        self.verticalLayout_7.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.soapLevelLabel = QtWidgets.QLabel(self.middleLeft)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.soapLevelLabel.setFont(font)
        self.soapLevelLabel.setStyleSheet("border: none;")
        self.soapLevelLabel.setObjectName("soapLevelLabel")
        self.verticalLayout_7.addWidget(self.soapLevelLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.soapLevelSensor = QtWidgets.QLabel(self.middleLeft)
        self.soapLevelSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.soapLevelSensor.setText("")
        self.soapLevelSensor.setPixmap(QtGui.QPixmap("icons8-soap-dispenser-80.png"))
        self.soapLevelSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.soapLevelSensor.setObjectName("soapLevelSensor")
        self.verticalLayout_7.addWidget(self.soapLevelSensor)
        self.horizontalLayout_5.addWidget(self.middleLeft)
        self.middleCenter = QtWidgets.QFrame(self.middle)
        self.middleCenter.setStyleSheet("border: 2px solid black;")
        self.middleCenter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middleCenter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.middleCenter.setObjectName("middleCenter")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.middleCenter)
        self.verticalLayout_8.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.humidityLabel = QtWidgets.QLabel(self.middleCenter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.humidityLabel.setFont(font)
        self.humidityLabel.setStyleSheet("border: none;")
        self.humidityLabel.setObjectName("humidityLabel")
        self.verticalLayout_8.addWidget(self.humidityLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.humidity = QtWidgets.QLCDNumber(self.middleCenter)
        self.humidity.setObjectName("humidity")
        self.verticalLayout_8.addWidget(self.humidity)
        self.horizontalLayout_5.addWidget(self.middleCenter)
        self.middleRight = QtWidgets.QFrame(self.middle)
        self.middleRight.setMinimumSize(QtCore.QSize(500, 0))
        self.middleRight.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.middleRight.setStyleSheet("border: 2px solid black;")
        self.middleRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middleRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middleRight.setObjectName("middleRight")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.middleRight)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.middleRightTop = QtWidgets.QFrame(self.middleRight)
        self.middleRightTop.setStyleSheet("border: none;")
        self.middleRightTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middleRightTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middleRightTop.setObjectName("middleRightTop")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.middleRightTop)
        self.verticalLayout_17.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pumpMotorStatus = QtWidgets.QLabel(self.middleRightTop)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pumpMotorStatus.setFont(font)
        self.pumpMotorStatus.setStyleSheet("border: none;")
        self.pumpMotorStatus.setObjectName("pumpMotorStatus")
        self.verticalLayout_17.addWidget(self.pumpMotorStatus, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pumpMotorLabels = QtWidgets.QFrame(self.middleRightTop)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pumpMotorLabels.setFont(font)
        self.pumpMotorLabels.setStyleSheet("border: none;")
        self.pumpMotorLabels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pumpMotorLabels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pumpMotorLabels.setObjectName("pumpMotorLabels")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.pumpMotorLabels)
        self.horizontalLayout_7.setContentsMargins(35, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(30)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.waterPumpLabel = QtWidgets.QLabel(self.pumpMotorLabels)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.waterPumpLabel.setFont(font)
        self.waterPumpLabel.setObjectName("waterPumpLabel")
        self.horizontalLayout_7.addWidget(self.waterPumpLabel)
        self.soapPumpLabel = QtWidgets.QLabel(self.pumpMotorLabels)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.soapPumpLabel.setFont(font)
        self.soapPumpLabel.setObjectName("soapPumpLabel")
        self.horizontalLayout_7.addWidget(self.soapPumpLabel)
        self.motorLabel = QtWidgets.QLabel(self.pumpMotorLabels)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.motorLabel.setFont(font)
        self.motorLabel.setObjectName("motorLabel")
        self.horizontalLayout_7.addWidget(self.motorLabel)
        self.verticalLayout_17.addWidget(self.pumpMotorLabels, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_9.addWidget(self.middleRightTop)
        self.middleRightDown = QtWidgets.QFrame(self.middleRight)
        self.middleRightDown.setEnabled(True)
        self.middleRightDown.setStyleSheet("border: none;")
        self.middleRightDown.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middleRightDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middleRightDown.setObjectName("middleRightDown")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.middleRightDown)
        self.horizontalLayout_6.setContentsMargins(5, 0, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.waterPump = QtWidgets.QFrame(self.middleRightDown)
        self.waterPump.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.waterPump.setFrameShadow(QtWidgets.QFrame.Raised)
        self.waterPump.setObjectName("waterPump")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.waterPump)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.waterPumpSensor = QtWidgets.QLabel(self.waterPump)
        self.waterPumpSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.waterPumpSensor.setText("")
        self.waterPumpSensor.setPixmap(QtGui.QPixmap("icons8-pump-100.png"))
        self.waterPumpSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.waterPumpSensor.setObjectName("waterPumpSensor")
        self.horizontalLayout_8.addWidget(self.waterPumpSensor)
        self.horizontalLayout_6.addWidget(self.waterPump)
        self.soapPump = QtWidgets.QFrame(self.middleRightDown)
        self.soapPump.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.soapPump.setFrameShadow(QtWidgets.QFrame.Raised)
        self.soapPump.setObjectName("soapPump")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.soapPump)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.soapPumpSensor = QtWidgets.QLabel(self.soapPump)
        self.soapPumpSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.soapPumpSensor.setText("")
        self.soapPumpSensor.setPixmap(QtGui.QPixmap("icons8-pump-100.png"))
        self.soapPumpSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.soapPumpSensor.setObjectName("soapPumpSensor")
        self.verticalLayout_10.addWidget(self.soapPumpSensor)
        self.horizontalLayout_6.addWidget(self.soapPump)
        self.motor = QtWidgets.QFrame(self.middleRightDown)
        self.motor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.motor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.motor.setObjectName("motor")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.motor)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.motorSensor = QtWidgets.QLabel(self.motor)
        self.motorSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"border-radius: 20px;\n"
"border: 4px solid black;")
        self.motorSensor.setText("")
        self.motorSensor.setPixmap(QtGui.QPixmap("icons8-stepper-motor-100.png"))
        self.motorSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.motorSensor.setObjectName("motorSensor")
        self.horizontalLayout_9.addWidget(self.motorSensor)
        self.horizontalLayout_6.addWidget(self.motor)
        self.verticalLayout_9.addWidget(self.middleRightDown)
        self.horizontalLayout_5.addWidget(self.middleRight)
        self.verticalLayout.addWidget(self.middle)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom.sizePolicy().hasHeightForWidth())
        self.bottom.setSizePolicy(sizePolicy)
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.bottom)
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_10.setContentsMargins(0, 8, 0, 8)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bottomLeft = QtWidgets.QFrame(self.bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomLeft.sizePolicy().hasHeightForWidth())
        self.bottomLeft.setSizePolicy(sizePolicy)
        self.bottomLeft.setStyleSheet("border: 2px solid black;")
        self.bottomLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomLeft.setObjectName("bottomLeft")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.bottomLeft)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.parameters = QtWidgets.QGroupBox(self.bottomLeft)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.parameters.setFont(font)
        self.parameters.setStyleSheet("border:none;")
        self.parameters.setTitle("")
        self.parameters.setFlat(False)
        self.parameters.setObjectName("parameters")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.parameters)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labels = QtWidgets.QFrame(self.parameters)
        self.labels.setStyleSheet("border: none;")
        self.labels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labels.setObjectName("labels")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.labels)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.CarTypeLabel = QtWidgets.QLabel(self.labels)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.CarTypeLabel.setFont(font)
        self.CarTypeLabel.setObjectName("CarTypeLabel")
        self.verticalLayout_12.addWidget(self.CarTypeLabel)
        self.overallCycleLabel = QtWidgets.QLabel(self.labels)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.overallCycleLabel.setFont(font)
        self.overallCycleLabel.setObjectName("overallCycleLabel")
        self.verticalLayout_12.addWidget(self.overallCycleLabel)
        self.delaySoap = QtWidgets.QLabel(self.labels)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.delaySoap.setFont(font)
        self.delaySoap.setObjectName("delaySoap")
        self.verticalLayout_12.addWidget(self.delaySoap)
        self.soapSprayCycle = QtWidgets.QLabel(self.labels)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.soapSprayCycle.setFont(font)
        self.soapSprayCycle.setObjectName("soapSprayCycle")
        self.verticalLayout_12.addWidget(self.soapSprayCycle)
        self.waterSprayCycle = QtWidgets.QLabel(self.labels)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.waterSprayCycle.setFont(font)
        self.waterSprayCycle.setObjectName("waterSprayCycle")
        self.verticalLayout_12.addWidget(self.waterSprayCycle)
        self.delayWater = QtWidgets.QLabel(self.labels)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.delayWater.setFont(font)
        self.delayWater.setObjectName("delayWater")
        self.verticalLayout_12.addWidget(self.delayWater)
        self.horizontalLayout_11.addWidget(self.labels)
        self.inputBoxes = QtWidgets.QFrame(self.parameters)
        self.inputBoxes.setStyleSheet("border:none;")
        self.inputBoxes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputBoxes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputBoxes.setObjectName("inputBoxes")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.inputBoxes)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.carType = QtWidgets.QComboBox(self.inputBoxes)
        self.carType.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carType.setObjectName("carType")
        self.carType.addItem("")
        self.carType.addItem("")
        self.carType.addItem("")
        self.verticalLayout_13.addWidget(self.carType)
        self.OC = QtWidgets.QSpinBox(self.inputBoxes)
        self.OC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OC.setObjectName("OC")
        self.verticalLayout_13.addWidget(self.OC)
        self.DS = QtWidgets.QSpinBox(self.inputBoxes)
        self.DS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DS.setObjectName("DS")
        self.verticalLayout_13.addWidget(self.DS)
        self.SSC = QtWidgets.QSpinBox(self.inputBoxes)
        self.SSC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SSC.setObjectName("SSC")
        self.verticalLayout_13.addWidget(self.SSC)
        self.WSC = QtWidgets.QSpinBox(self.inputBoxes)
        self.WSC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WSC.setObjectName("WSC")
        self.verticalLayout_13.addWidget(self.WSC)
        self.DW = QtWidgets.QSpinBox(self.inputBoxes)
        self.DW.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DW.setObjectName("DW")
        self.verticalLayout_13.addWidget(self.DW)
        self.horizontalLayout_11.addWidget(self.inputBoxes)
        self.verticalLayout_11.addWidget(self.parameters)
        self.buttons = QtWidgets.QFrame(self.bottomLeft)
        self.buttons.setStyleSheet("border: none;")
        self.buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Start = QtWidgets.QFrame(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start.sizePolicy().hasHeightForWidth())
        self.Start.setSizePolicy(sizePolicy)
        self.Start.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Start.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Start.setObjectName("Start")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.Start)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.start = QtWidgets.QPushButton(self.Start)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color: rgb(5, 255, 193);\n"
"border-radius: 25px;\n"
" border: 2px solid black;\n"
"height: 50px;\n"
"width: 50px;\n"
"")
        self.start.setObjectName("start")
        self.horizontalLayout_13.addWidget(self.start)
        self.horizontalLayout_12.addWidget(self.Start)
        self.animateButton = QtWidgets.QFrame(self.buttons)
        self.animateButton.setStyleSheet("border-radius: 50px;")
        self.animateButton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.animateButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.animateButton.setObjectName("animateButton")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.animateButton)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.update = QtWidgets.QPushButton(self.animateButton)
        self.update.setStyleSheet("background-color:rgb(255, 0, 127);\n"
"border: 2px solid black;")
        self.update.setText("")
        self.update.setObjectName("update")
        self.horizontalLayout_14.addWidget(self.update)
        self.notDefined2 = QtWidgets.QPushButton(self.animateButton)
        self.notDefined2.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"")
        self.notDefined2.setText("")
        self.notDefined2.setObjectName("notDefined2")
        self.horizontalLayout_14.addWidget(self.notDefined2)
        self.notDefined1 = QtWidgets.QPushButton(self.animateButton)
        self.notDefined1.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"")
        self.notDefined1.setText("")
        self.notDefined1.setObjectName("notDefined1")
        self.horizontalLayout_14.addWidget(self.notDefined1)
        self.IO = QtWidgets.QPushButton(self.animateButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IO.sizePolicy().hasHeightForWidth())
        self.IO.setSizePolicy(sizePolicy)
        self.IO.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"")
        self.IO.setText("")
        self.IO.setObjectName("IO")
        self.horizontalLayout_14.addWidget(self.IO)
        self.horizontalLayout_12.addWidget(self.animateButton, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_11.addWidget(self.buttons)
        self.horizontalLayout_10.addWidget(self.bottomLeft)
        self.bottomRight = QtWidgets.QFrame(self.bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomRight.sizePolicy().hasHeightForWidth())
        self.bottomRight.setSizePolicy(sizePolicy)
        self.bottomRight.setStyleSheet("border: 2px solid black;")
        self.bottomRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRight.setObjectName("bottomRight")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.bottomRight)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.bottomFrameBottom = QtWidgets.QFrame(self.bottomRight)
        self.bottomFrameBottom.setStyleSheet("border: none;")
        self.bottomFrameBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomFrameBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrameBottom.setObjectName("bottomFrameBottom")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.bottomFrameBottom)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.progressLabel = QtWidgets.QLabel(self.bottomFrameBottom)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.progressLabel.setFont(font)
        self.progressLabel.setStyleSheet("border: none;")
        self.progressLabel.setObjectName("progressLabel")
        self.verticalLayout_18.addWidget(self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(self.bottomFrameBottom)
        self.progressBar.setStyleSheet("border: 2px solid black; \n"
"background-color: rgb(4, 217, 15); \n")     
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_18.addWidget(self.progressBar)
        self.verticalLayout_14.addWidget(self.bottomFrameBottom, 0, QtCore.Qt.AlignVCenter)
        self.bottomRightTop = QtWidgets.QFrame(self.bottomRight)
        self.bottomRightTop.setStyleSheet("border: none;")
        self.bottomRightTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomRightTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRightTop.setObjectName("bottomRightTop")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.bottomRightTop)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.operationLabel = QtWidgets.QLabel(self.bottomRightTop)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.operationLabel.setFont(font)
        self.operationLabel.setStyleSheet("border: none;")
        self.operationLabel.setObjectName("operationLabel")
        self.verticalLayout_15.addWidget(self.operationLabel)
        self.operationMessageDisp = QtWidgets.QLabel(self.bottomRightTop)
        self.operationMessageDisp.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.operationMessageDisp.setFont(font)
        self.operationMessageDisp.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(194, 194, 194);\n"
"border-radius: 20px;\n"
"")
        self.operationMessageDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.operationMessageDisp.setObjectName("operationMessageDisp")
        self.verticalLayout_15.addWidget(self.operationMessageDisp)
        self.verticalLayout_14.addWidget(self.bottomRightTop)
        self.bottomRightMiddle = QtWidgets.QFrame(self.bottomRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomRightMiddle.sizePolicy().hasHeightForWidth())
        self.bottomRightMiddle.setSizePolicy(sizePolicy)
        self.bottomRightMiddle.setStyleSheet("border: none;")
        self.bottomRightMiddle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomRightMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRightMiddle.setObjectName("bottomRightMiddle")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.bottomRightMiddle)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.faultMessageLabel = QtWidgets.QLabel(self.bottomRightMiddle)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.faultMessageLabel.setFont(font)
        self.faultMessageLabel.setStyleSheet("border: none;")
        self.faultMessageLabel.setObjectName("faultMessageLabel")
        self.verticalLayout_16.addWidget(self.faultMessageLabel)
        self.faultMessageDisp = QtWidgets.QLabel(self.bottomRightMiddle)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.faultMessageDisp.setFont(font)
        self.faultMessageDisp.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(194, 194, 194);\n"
"border-radius: 20px;\n"
"")
        self.faultMessageDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.faultMessageDisp.setObjectName("faultMessageDisp")
        self.verticalLayout_16.addWidget(self.faultMessageDisp)
        self.verticalLayout_14.addWidget(self.bottomRightMiddle)
        self.horizontalLayout_10.addWidget(self.bottomRight)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.WSC.setValue(1)
        self.SSC.setValue(1)
        self.DW.setValue(5)
        self.DS.setValue(5)
        self.OC.setValue(1)
        self.temperature.display(0)
        self.humidity.display(0)
        self.start.clicked.connect(self.start_process)
        self.update.clicked.connect(self.update_process)
        self.IO.clicked.connect(self.io_diagnostic)
        self.progressBar.setValue(0)
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.waterLevelLabel.setText(_translate("MainWindow", "Water Level"))
        self.tempLabel.setText(_translate("MainWindow", "Temperature \'C"))
        self.sensorStatusLabel.setText(_translate("MainWindow", "Sensors Status"))
        self.homeSensorLabel.setText(_translate("MainWindow", "HOME"))
        self.forwardSensoLabel.setText(_translate("MainWindow", "FORWARD"))
        self.reverseSensorLabel.setText(_translate("MainWindow", "REVERSE"))
        self.soapLevelLabel.setText(_translate("MainWindow", "Soap Level"))
        self.humidityLabel.setText(_translate("MainWindow", "Humidity %"))
        self.pumpMotorStatus.setText(_translate("MainWindow", "Pumps & Motor Status"))
        self.waterPumpLabel.setText(_translate("MainWindow", "Water Pump"))
        self.soapPumpLabel.setText(_translate("MainWindow", "Soap Pump"))
        self.motorLabel.setText(_translate("MainWindow", "Motor"))
        self.CarTypeLabel.setText(_translate("MainWindow", "Car Type"))
        self.overallCycleLabel.setText(_translate("MainWindow", "Overall Cycles"))
        self.delaySoap.setText(_translate("MainWindow", "Delay Soap (Sec)"))
        self.soapSprayCycle.setText(_translate("MainWindow", "Soap Spray Cycle"))
        self.waterSprayCycle.setText(_translate("MainWindow", "Water Spray Cycle"))
        self.delayWater.setText(_translate("MainWindow", "Delay Water (Sec)"))
        self.carType.setItemText(0, _translate("MainWindow", "MiniCar"))
        self.carType.setItemText(1, _translate("MainWindow", "Sedan"))
        self.carType.setItemText(2, _translate("MainWindow", "MPV"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.progressLabel.setText(_translate("MainWindow", "Progress"))
        self.operationLabel.setText(_translate("MainWindow", "Operation"))
        self.operationMessageDisp.setText(_translate("MainWindow", "  Current Operation..."))
        self.faultMessageLabel.setText(_translate("MainWindow", "Fault Messages"))
        self.faultMessageDisp.setText(_translate("MainWindow", "  Fault Messages..."))

    def io_diagnostic(self):
        io_diagnostic_msg = QMessageBox()
        io_diagnostic_msg.setWindowTitle("IO Diagnostic")
        io_diagnostic_msg.setText("Do you wanna run IO Diagnostic")
        io_diagnostic_msg.setIcon(QMessageBox.Question) 
        io_diagnostic_msg.setStandardButtons(QMessageBox.Cancel|QMessageBox.Ok)
        io_diagnostic_msg.setDefaultButton(QMessageBox.Ok)
        io_diagnostic_msg.exec_()

    def stop_process(self):
        stop_msg = QMessageBox()
        stop_msg.setWindowTitle("Warning")
        stop_msg.setText("Do you want to Halt the Process?")
        stop_msg.setIcon(QMessageBox.Question)
        stop_msg.setStandardButtons(QMessageBox.Cancel|QMessageBox.Ok)
        stop_msg.setDefaultButton(QMessageBox.Ok)
        stop_msg.exec_()
            
    def update_process(self):
        global finish
        print("update")
        line2 =""
        while True:
            line2 = ser.readline().decode('utf-8').rstrip()
            print(line2)
            #time.sleep(1)

############  Water Levels ################
            global chk
            if line2 == "WLL" and chk == 0:
                print(line2)
                print(chk)
                self.waterLevelSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(245, 10, 10);")
                self.faultMessageDisp.setText("")
                ser.write(b"PiRec0\n")
                #time.sleep(1);
                line2= ""
                chk = 1
                break
            
            if line2 == "WLF" and chk == 0:
                print(line2)
                print(chk)
                self.waterLevelSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(245, 10, 10);")
                self.faultMessageDisp.setText("Water Level Sensor Fault !!!")
                ser.write(b"PiRec0\n")
                #time.sleep(1);
                line2= ""
                chk = 1
                break
            
            if line2 == "WLH" and chk == 0:
                print(line2)
                print(chk)
                self.waterLevelSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(78, 245, 66);")
                self.faultMessageDisp.setText("")
                ser.write(b"PiRec0\n")
                #time.sleep(1);
                line2= ""
                chk = 1
                break

            if line2 == "SLL" and chk == 1:
                print(line2)
                print(chk)
                self.soapLevelSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(245, 10, 10);")
                self.faultMessageDisp.setText("")
                ser.write(b"PiRec1\n")
                #time.sleep(1);
                line2= ""
                chk = 2
                break;
            
            if line2 == "SLF" and chk == 1:
                print(line2)
                print(chk)
                self.soapLevelSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(245, 10, 10);")
                self.faultMessageDisp.setText("Soap Level Sensor Fault !!!")
                ser.write(b"PiRec1\n")
                #time.sleep(1);
                line2= ""
                chk = 2
                break;
            
            if line2 == "SLH" and chk == 1:
                print(line2)
                print(chk)
                self.soapLevelSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(78, 245, 66);")
                self.faultMessageDisp.setText("")
                ser.write(b"PiRec1\n")
                #time.sleep(1);
                line2= ""
                chk = 2
                break;
            
            if chk == 2:
                if len(line2) > 0:
                 if line2[0] == "t":
                   l= len(line2)
                   if l == 1:
                      signalTemp = line2[1]
                   else:
                      signalTemp= line2[1:l]
                   
                   print(signalTemp)
                   print(chk)
                   self.temperature.display(int(signalTemp))
                   if int(signalTemp) == 0:
                       self.faultMessageDisp.setText("DHT11 Sensor Fault !!!")
                   else:
                       self.faultMessageDisp.setText("")
                   ser.write(b"PiRec2\n")
                   #time.sleep(1);
                   line2= ""
                   chk = 3
                   break;
            
            if  chk == 3:
                if len(line2) > 0:
                 if line2[0] == "h":
                   l= len(line2)
                   if l == 1:
                      signalHum = line2[1]
                   else:
                      signalHum = line2[1:l]
                   print(signalHum)
                   print(chk)
                   self.humidity.display(int(signalHum))
                   if int(signalHum) == 0:
                       self.faultMessageDisp.setText("DHT11 Sensor Fault !!!")
                   else:
                       self.faultMessageDisp.setText("")
                   ser.write(b"PiRec3\n")
                   #time.sleep(1);
                   line2= ""
                   chk = 4
                   break;
                
            if line2 == "MF" and chk == 4:
                print(line2)
                print(chk)
                self.motorSensor.setStyleSheet("background-color: rgb(157, 157, 157);\n"
                "border-radius: 20px;\n"
                "border: 4px solid black;")
                ser.write(b"PiRec4\n")
                #time.sleep(1);
                line2= ""
                chk = 5
                break;
            
            if line2 == "MO" and chk == 4:
                print(line2)
                print(chk)
                self.motorSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(78, 245, 66);")
                ser.write(b"PiRec4\n")
                #time.sleep(1);
                line2= ""
                chk = 5
                break;
            
            if line2 == "SSH" and chk == 5:
                print(line2)
                print(chk)
                self.homeSensor.setStyleSheet("background-color: rgb(78, 245, 66);\n"
                "border-radius: 20px;\n"
                "border: 4px solid black;")
                ser.write(b"PiRec5\n")
                #time.sleep(1);
                line2= ""
                chk = 6
                break;
            
            if line2 == "NSH" and chk == 5:
                print(line2)
                print(chk)
                self.homeSensor.setStyleSheet("background-color: rgb(157,157,157);\n"
                "border-radius: 20px;\n"
                "border: 4px solid black;")
                ser.write(b"PiRec5\n")
                #time.sleep(1);
                line2= ""
                chk = 6
                break;
            
            if line2 == "SSF" and chk == 6:
                print(line2)
                print(chk)
                self.forwardSensor.setStyleSheet("background-color: rgb(78, 245, 66);\n"
                "border-radius: 20px;\n"
                "border: 4px solid black;")
                ser.write(b"PiRec6\n")
                #time.sleep(1);
                line2= ""
                chk = 7
                break;
            
            if line2 == "NSF" and chk == 6:
                print(line2)
                print(chk)
                self.forwardSensor.setStyleSheet("background-color: rgb(157,157,157);\n"
                "border-radius: 20px;\n"
                "border: 4px solid black;")
                ser.write(b"PiRec6\n")
                #time.sleep(1);
                line2= ""
                chk = 7
                break;
            
            if line2 == "SSR" and chk == 7:
                print(line2)
                print(chk)
                self.reverseSensor.setStyleSheet("background-color: rgb(78, 245, 66);\n"
                "border-radius: 20px;\n"
                "border: 4px solid black;")
                ser.write(b"PiRec7\n")
                #time.sleep(1);
                line2= ""
                chk = 8
                break;
            
            if line2 == "NSR" and chk == 7:
                print(line2)
                print(chk)
                self.reverseSensor.setStyleSheet("background-color: rgb(157,157,157);\n"
                "border-radius: 20px;\n"
                "border: 4px solid black;")
                ser.write(b"PiRec7\n")
                #time.sleep(1);
                line2= ""
                chk = 8
                break;
            
            if line2 == "WPO" and chk == 8:
                print(line2)
                print(chk)
                self.waterPumpSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(78, 245, 66);")
                ser.write(b"PiRec8\n")
                #time.sleep(1);
                line2= ""
                chk = 9
                break;
            
            if line2 == "WPF" and chk == 8:
                print(line2)
                print(chk)
                self.waterPumpSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(157, 157, 157);")
                ser.write(b"PiRec8\n")
                #time.sleep(1);
                line2= ""
                chk = 9
                break;
            
            if line2 == "SPO" and chk == 9:
                print(line2)
                print(chk)
                self.soapPumpSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(78, 245, 66);")
                ser.write(b"PiRec9\n")
                #time.sleep(1);
                line2= ""
                chk = 10
                break;
            
            if line2 == "SPF" and chk == 9:
                print(line2)
                print(chk)
                self.soapPumpSensor.setStyleSheet("border-radius: 20px;\n"
                "border: 4px solid black;\n"
                "background-color: rgb(157, 157, 157);")
                ser.write(b"PiRec9\n")
                #time.sleep(1);
                line2= ""
                chk = 10
                break;
            
            if chk == 10:
                if len(line2) > 0:
                 if line2[0] == "p":
                   l= len(line2)
                   if l == 1:
                      progress = line2[1]
                   else:
                      progress = line2[1:l]
                   
                   print(progress)
                   print(chk)
                   self.operationMessageDisp.setText(progress)
                   ser.write(b"PiRec10\n")
                   #time.sleep(1);
                   line2= ""
                   chk = 11
                   break;
            
            if chk == 11:
                if len(line2) > 0:
                 if line2[0] == "g":
                   l= len(line2)
                   if l == 1:
                      percentage = line2[1]
                   else:
                      percentage = line2[1:l]
                   
                   print(percentage)
                   print(chk)
                   self.progressBar.setValue(int(percentage))
                   ser.write(b"PiRec11\n")
                   #time.sleep(1);
                   line2= ""
                   chk = 12
                   break;
            
            if line2 == "FIN" and chk == 12:
                print(line2)
                print(chk)
                finish = 1
                self.progressBar.setValue(100)
                self.operationMessageDisp.setText("Car Washed !!!")
                ser.write(b"PiRec12\n")
                time.sleep(3);
                self.operationMessageDisp.setText("")
                self.progressBar.setValue(0)
                line2= ""
                chk = 0
                break;
            
            if line2 == "NFIN" and chk == 12:
                print(line2)
                print(chk)
                ser.write(b"PiRec12\n")
                #time.sleep(1);
                line2= ""
                chk = 0
                break
    
            

        #time.sleep(3)
        if finish == 0:
          self.update.animateClick()
        if finish == 1:
            finish = 0
    
    def start_process(self):
        
        carType = self.carType.currentText()
        wsc = self.WSC.value()
        ssc = self.SSC.value()
        dw = self.DW.value()
        ds = self.DS.value()
        oc = self.OC.value()

        self.operationMessageDisp.setText("Waiting to Start")
        self.faultMessageDisp.setText("")

        msg = QMessageBox()
        msg.setWindowTitle("Car Wash Parameters")
        msg.setText("Overall Cycles: "+str(oc)+"\nWater Spray Cycle: "+str(wsc)+
            "\nSoap Spray Cycle: "+str(ssc)+"\nDelay Water: "+str(dw)+"\nDelay Soap: "+str(ds))
        msg.setInformativeText("Car Type "+ carType + " is selected!")
        msg.setInformativeText("Car Type "+ carType + " is selected!")
        msg.setIcon(QMessageBox.Information)                  
        x  = msg.exec_()   


        ############Communication Code###############
        #ser = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
        #ser.flush()
        msg="\n"
        chk_serial = 0
        print("start")
        ser = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
        ser.flush()
        while True:
          if chk_serial == 0:
            ser.write(carType.encode('utf-8'))
            ser.write(msg.encode('utf-8'))

            line = ser.readline().decode('utf-8').rstrip()
            print(line)
            #time.sleep(1)
            if line == "car_rec":
              chk_serial = 1
          if chk_serial == 1:
            ser.write(str(wsc).encode('utf-8'))
            ser.write(msg.encode('utf-8'))

            line = ser.readline().decode('utf-8').rstrip()
            print(line)
            #time.sleep(1)
            if line == "wsc_rec":
              chk_serial = 2
          if chk_serial == 2:
            ser.write(str(ssc).encode('utf-8'))
            ser.write(msg.encode('utf-8'))

            line = ser.readline().decode('utf-8').rstrip()
            print(line)
            #time.sleep(1)
            if line == "ssc_rec":
              chk_serial = 3
          if chk_serial == 3:
            ser.write(str(dw).encode('utf-8'))
            ser.write(msg.encode('utf-8'))

            line = ser.readline().decode('utf-8').rstrip()
            print(line)
            #time.sleep(1)
            if line == "dw_rec":
              chk_serial = 4
          if chk_serial == 4:
            ser.write(str(ds).encode('utf-8'))
            ser.write(msg.encode('utf-8'))

            line = ser.readline().decode('utf-8').rstrip()
            print(line)
            #time.sleep(1)
            if line == "ds_rec":
              chk_serial = 5
          if chk_serial == 5:
              
            ser.write(str(oc).encode('utf-8'))
            ser.write(msg.encode('utf-8'))
            line = ser.readline().decode('utf-8').rstrip()
            print(line)
            if line == "oc_rec":
              chk_serial = 6
              self.update.animateClick()
              break; 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
